  services:
    login:
      build: ./images/login/.
      hostname: login
      environment:
        - NODE_ROLE=login
      volumes:
        - ./credentials/munge/munge.key:/tmp/munge.key:ro
        - ./credentials/slurm:/etc/slurm:ro
        - ./shared-files:/app
        
    controller:
      build: ./images/controller/.
      hostname: controller
      ports: 
        - "9090:9090"
      environment:
        - NODE_ROLE=controller
      volumes:
        - ./credentials/munge/munge.key:/tmp/munge.key:ro
        - ./credentials/slurm:/etc/slurm:ro
        - ./credentials/prometheus:/etc/prometheus:ro
        - ./shared-files:/app

    compute-1:
      build: ./images/compute/.
      hostname: compute-1
      privileged: true
      environment:
        - NODE_ROLE=compute
      volumes:
        - ./credentials/munge/munge.key:/tmp/munge.key:ro
        - ./credentials/slurm:/etc/slurm:ro
        - ./shared-files:/app

    compute-2:
      build: ./images/compute/.
      hostname: compute-2
      privileged: true
      environment:
        - NODE_ROLE=compute
      volumes:
        - ./credentials/munge/munge.key:/tmp/munge.key:ro
        - ./credentials/slurm:/etc/slurm:ro
        - ./shared-files:/app