global:
  scrape_interval: 30s # Frequência de coleta de métricas
  scrape_timeout: 30s # Tempo limite para aguardar a resposta do endpoint
  evaluation_interval: 30s # Frequência para a avaliação de regras de alarme

scrape_configs:

   # Coletas das métricas do próprio servidor Prometheus
  - job_name: 'prometheus'
    static_configs: 
      - targets: ['localhost:9090']
    
  # Metricas de Tarefas e Alocações do Slurm 
  - job_name: 'slurm_jobs'
    metrics_path: '/metrics/jobs'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:6817']

    # Métricas de Estado do Nós do Slurm
  - job_name: 'slurm_nodes'
    metrics_path: '/metrics/nodes'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs: 
      - targets: ['localhost:6817']


  # Métricas de Partição e Filas do Slurm
  - job_name: 'slurm_partitions'
    metrics_path: '/metrics/partitions'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:6817']

  # Diagnóstico do Scheduler Slurm (sdiag e backfill)
  - job_name: 'slurm_scheduler'
    metrics_path: '/metrics/scheduler'
    scrape_interval: 10s # Endpoint com maior volatilidade (maiores alterações constantes)
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:6817']    


